List<Map<String, String>> allFonts = [
  {'font': 'Roboto', 'bgColor': '0xffF1E9E5'},
  {'font': 'Poppins', 'bgColor': '0xffB7C4CF'},
  {'font': 'Lato', 'bgColor': '0xffEEE3CB'},
  {'font': 'Inter', 'bgColor': '0xffD7C0AE'},
  {'font': 'Oswald', 'bgColor': '0xff967E76'},
  {'font': 'Raleway', 'bgColor': '0xff60A9A6'},
  {'font': 'Montserrat', 'bgColor': '0xffCAF2D7'},
  {'font': 'Merriweather', 'bgColor': '0xffDFE2E2'},
  {'font': 'Kanit', 'bgColor': '0xffD9EEEC'},
  {'font': 'Lora', 'bgColor': '0xffF6E7C1'},
  {'font': 'Teko', 'bgColor': '0xff7EB19F'},
  {'font': 'Mulish', 'bgColor': '0xffDBE9B7'},
  {'font': 'Barlow', 'bgColor': '0xffFFF6EA'},
  {'font': 'Quicksand', 'bgColor': '0xff8CA1A5'},
  {'font': 'Inconsolata', 'bgColor': '0xffE2BCB7'},
  {'font': 'Karla', 'bgColor': '0xffD9D7F1'},
  {'font': 'Dosis', 'bgColor': '0xffBFDCE5'},
  {'font': 'Dokdo', 'bgColor': '0xffEEEEEE'},
  {'font': 'Caveat', 'bgColor': '0xffFF8882'},
  {'font': 'Gaegu', 'bgColor': '0xffFFC2B4'},
];
